// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8KHyWSXhknAYUB1pm44NeGZe6J7lvNTo',
    appId: '1:579433838100:web:9e57ace7dd23e896b39901',
    messagingSenderId: '579433838100',
    projectId: 'whatsapp-fcm-lab-d496d',
    authDomain: 'whatsapp-fcm-lab-d496d.firebaseapp.com',
    storageBucket: 'whatsapp-fcm-lab-d496d.firebasestorage.app',
    measurementId: 'G-LCCWYMYBXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoSUGCd5KZjKowvxFkMNKNrhag7ie4dgI',
    appId: '1:579433838100:android:73ed246f47c6f4b3b39901',
    messagingSenderId: '579433838100',
    projectId: 'whatsapp-fcm-lab-d496d',
    storageBucket: 'whatsapp-fcm-lab-d496d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8n2r-WfOteHXeza_GxivsGGdaqRIxbuo',
    appId: '1:579433838100:ios:73516e3f6a16933bb39901',
    messagingSenderId: '579433838100',
    projectId: 'whatsapp-fcm-lab-d496d',
    storageBucket: 'whatsapp-fcm-lab-d496d.firebasestorage.app',
    iosBundleId: 'com.example.whatsappFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8n2r-WfOteHXeza_GxivsGGdaqRIxbuo',
    appId: '1:579433838100:ios:73516e3f6a16933bb39901',
    messagingSenderId: '579433838100',
    projectId: 'whatsapp-fcm-lab-d496d',
    storageBucket: 'whatsapp-fcm-lab-d496d.firebasestorage.app',
    iosBundleId: 'com.example.whatsappFcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8KHyWSXhknAYUB1pm44NeGZe6J7lvNTo',
    appId: '1:579433838100:web:5d561222a908fcb1b39901',
    messagingSenderId: '579433838100',
    projectId: 'whatsapp-fcm-lab-d496d',
    authDomain: 'whatsapp-fcm-lab-d496d.firebaseapp.com',
    storageBucket: 'whatsapp-fcm-lab-d496d.firebasestorage.app',
    measurementId: 'G-VNC8B2WZCD',
  );
}
